name: saltstack-salt-formula
source: https://github.com/bechtoldt/saltstack-salt-formula
summary: SaltStack Formula to set up and configure the central system and configuration manager SaltStack itself
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - 'minion/ master: Provide more flexible setting of configuration?'
  - 'master: create salt tree (for states and pillar)'
  - 'manage autosign file'
